//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialRequirements.GeneralService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GeneralService.GeneralSoap")]
    public interface GeneralSoap {
        
        // CODEGEN: Generating message contract since element name encUsername from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LatestActivityFeed", ReplyAction="*")]
        SocialRequirements.GeneralService.LatestActivityFeedResponse LatestActivityFeed(SocialRequirements.GeneralService.LatestActivityFeedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LatestActivityFeed", ReplyAction="*")]
        System.Threading.Tasks.Task<SocialRequirements.GeneralService.LatestActivityFeedResponse> LatestActivityFeedAsync(SocialRequirements.GeneralService.LatestActivityFeedRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LatestActivityFeedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LatestActivityFeed", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.GeneralService.LatestActivityFeedRequestBody Body;
        
        public LatestActivityFeedRequest() {
        }
        
        public LatestActivityFeedRequest(SocialRequirements.GeneralService.LatestActivityFeedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LatestActivityFeedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string encUsername;
        
        public LatestActivityFeedRequestBody() {
        }
        
        public LatestActivityFeedRequestBody(string encUsername) {
            this.encUsername = encUsername;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LatestActivityFeedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LatestActivityFeedResponse", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.GeneralService.LatestActivityFeedResponseBody Body;
        
        public LatestActivityFeedResponse() {
        }
        
        public LatestActivityFeedResponse(SocialRequirements.GeneralService.LatestActivityFeedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LatestActivityFeedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LatestActivityFeedResult;
        
        public LatestActivityFeedResponseBody() {
        }
        
        public LatestActivityFeedResponseBody(string LatestActivityFeedResult) {
            this.LatestActivityFeedResult = LatestActivityFeedResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GeneralSoapChannel : SocialRequirements.GeneralService.GeneralSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GeneralSoapClient : System.ServiceModel.ClientBase<SocialRequirements.GeneralService.GeneralSoap>, SocialRequirements.GeneralService.GeneralSoap {
        
        public GeneralSoapClient() {
        }
        
        public GeneralSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GeneralSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneralSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneralSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocialRequirements.GeneralService.LatestActivityFeedResponse SocialRequirements.GeneralService.GeneralSoap.LatestActivityFeed(SocialRequirements.GeneralService.LatestActivityFeedRequest request) {
            return base.Channel.LatestActivityFeed(request);
        }
        
        public string LatestActivityFeed(string encUsername) {
            SocialRequirements.GeneralService.LatestActivityFeedRequest inValue = new SocialRequirements.GeneralService.LatestActivityFeedRequest();
            inValue.Body = new SocialRequirements.GeneralService.LatestActivityFeedRequestBody();
            inValue.Body.encUsername = encUsername;
            SocialRequirements.GeneralService.LatestActivityFeedResponse retVal = ((SocialRequirements.GeneralService.GeneralSoap)(this)).LatestActivityFeed(inValue);
            return retVal.Body.LatestActivityFeedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SocialRequirements.GeneralService.LatestActivityFeedResponse> SocialRequirements.GeneralService.GeneralSoap.LatestActivityFeedAsync(SocialRequirements.GeneralService.LatestActivityFeedRequest request) {
            return base.Channel.LatestActivityFeedAsync(request);
        }
        
        public System.Threading.Tasks.Task<SocialRequirements.GeneralService.LatestActivityFeedResponse> LatestActivityFeedAsync(string encUsername) {
            SocialRequirements.GeneralService.LatestActivityFeedRequest inValue = new SocialRequirements.GeneralService.LatestActivityFeedRequest();
            inValue.Body = new SocialRequirements.GeneralService.LatestActivityFeedRequestBody();
            inValue.Body.encUsername = encUsername;
            return ((SocialRequirements.GeneralService.GeneralSoap)(this)).LatestActivityFeedAsync(inValue);
        }
    }
}
