//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialRequirements.ProjectService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProjectService.ProjectSoap")]
    public interface ProjectSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddProject", ReplyAction="*")]
        SocialRequirements.ProjectService.AddProjectResponse AddProject(SocialRequirements.ProjectService.AddProjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddProject", ReplyAction="*")]
        System.Threading.Tasks.Task<SocialRequirements.ProjectService.AddProjectResponse> AddProjectAsync(SocialRequirements.ProjectService.AddProjectRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddProjectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddProject", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.ProjectService.AddProjectRequestBody Body;
        
        public AddProjectRequest() {
        }
        
        public AddProjectRequest(SocialRequirements.ProjectService.AddProjectRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddProjectRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long companyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string encUsername;
        
        public AddProjectRequestBody() {
        }
        
        public AddProjectRequestBody(string name, string description, long companyId, string encUsername) {
            this.name = name;
            this.description = description;
            this.companyId = companyId;
            this.encUsername = encUsername;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddProjectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddProjectResponse", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.ProjectService.AddProjectResponseBody Body;
        
        public AddProjectResponse() {
        }
        
        public AddProjectResponse(SocialRequirements.ProjectService.AddProjectResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddProjectResponseBody {
        
        public AddProjectResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProjectSoapChannel : SocialRequirements.ProjectService.ProjectSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProjectSoapClient : System.ServiceModel.ClientBase<SocialRequirements.ProjectService.ProjectSoap>, SocialRequirements.ProjectService.ProjectSoap {
        
        public ProjectSoapClient() {
        }
        
        public ProjectSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProjectSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocialRequirements.ProjectService.AddProjectResponse SocialRequirements.ProjectService.ProjectSoap.AddProject(SocialRequirements.ProjectService.AddProjectRequest request) {
            return base.Channel.AddProject(request);
        }
        
        public void AddProject(string name, string description, long companyId, string encUsername) {
            SocialRequirements.ProjectService.AddProjectRequest inValue = new SocialRequirements.ProjectService.AddProjectRequest();
            inValue.Body = new SocialRequirements.ProjectService.AddProjectRequestBody();
            inValue.Body.name = name;
            inValue.Body.description = description;
            inValue.Body.companyId = companyId;
            inValue.Body.encUsername = encUsername;
            SocialRequirements.ProjectService.AddProjectResponse retVal = ((SocialRequirements.ProjectService.ProjectSoap)(this)).AddProject(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SocialRequirements.ProjectService.AddProjectResponse> SocialRequirements.ProjectService.ProjectSoap.AddProjectAsync(SocialRequirements.ProjectService.AddProjectRequest request) {
            return base.Channel.AddProjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<SocialRequirements.ProjectService.AddProjectResponse> AddProjectAsync(string name, string description, long companyId, string encUsername) {
            SocialRequirements.ProjectService.AddProjectRequest inValue = new SocialRequirements.ProjectService.AddProjectRequest();
            inValue.Body = new SocialRequirements.ProjectService.AddProjectRequestBody();
            inValue.Body.name = name;
            inValue.Body.description = description;
            inValue.Body.companyId = companyId;
            inValue.Body.encUsername = encUsername;
            return ((SocialRequirements.ProjectService.ProjectSoap)(this)).AddProjectAsync(inValue);
        }
    }
}
