//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialRequirements.ProjectService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfLong", Namespace="http://tempuri.org/", ItemName="long")]
    [System.SerializableAttribute()]
    public class ArrayOfLong : System.Collections.Generic.List<long> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProjectService.ProjectSoap")]
    public interface ProjectSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddProject", ReplyAction="*")]
        SocialRequirements.ProjectService.AddProjectResponse AddProject(SocialRequirements.ProjectService.AddProjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddProject", ReplyAction="*")]
        System.Threading.Tasks.Task<SocialRequirements.ProjectService.AddProjectResponse> AddProjectAsync(SocialRequirements.ProjectService.AddProjectRequest request);
        
        // CODEGEN: Generating message contract since element name companiesIdList from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByCompanies", ReplyAction="*")]
        SocialRequirements.ProjectService.GetByCompaniesResponse GetByCompanies(SocialRequirements.ProjectService.GetByCompaniesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByCompanies", ReplyAction="*")]
        System.Threading.Tasks.Task<SocialRequirements.ProjectService.GetByCompaniesResponse> GetByCompaniesAsync(SocialRequirements.ProjectService.GetByCompaniesRequest request);
        
        // CODEGEN: Generating message contract since element name GetByCompanyResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByCompany", ReplyAction="*")]
        SocialRequirements.ProjectService.GetByCompanyResponse GetByCompany(SocialRequirements.ProjectService.GetByCompanyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByCompany", ReplyAction="*")]
        System.Threading.Tasks.Task<SocialRequirements.ProjectService.GetByCompanyResponse> GetByCompanyAsync(SocialRequirements.ProjectService.GetByCompanyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddProjectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddProject", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.ProjectService.AddProjectRequestBody Body;
        
        public AddProjectRequest() {
        }
        
        public AddProjectRequest(SocialRequirements.ProjectService.AddProjectRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddProjectRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long companyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string encUsername;
        
        public AddProjectRequestBody() {
        }
        
        public AddProjectRequestBody(string name, string description, long companyId, string encUsername) {
            this.name = name;
            this.description = description;
            this.companyId = companyId;
            this.encUsername = encUsername;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddProjectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddProjectResponse", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.ProjectService.AddProjectResponseBody Body;
        
        public AddProjectResponse() {
        }
        
        public AddProjectResponse(SocialRequirements.ProjectService.AddProjectResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddProjectResponseBody {
        
        public AddProjectResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByCompaniesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByCompanies", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.ProjectService.GetByCompaniesRequestBody Body;
        
        public GetByCompaniesRequest() {
        }
        
        public GetByCompaniesRequest(SocialRequirements.ProjectService.GetByCompaniesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByCompaniesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SocialRequirements.ProjectService.ArrayOfLong companiesIdList;
        
        public GetByCompaniesRequestBody() {
        }
        
        public GetByCompaniesRequestBody(SocialRequirements.ProjectService.ArrayOfLong companiesIdList) {
            this.companiesIdList = companiesIdList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByCompaniesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByCompaniesResponse", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.ProjectService.GetByCompaniesResponseBody Body;
        
        public GetByCompaniesResponse() {
        }
        
        public GetByCompaniesResponse(SocialRequirements.ProjectService.GetByCompaniesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByCompaniesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetByCompaniesResult;
        
        public GetByCompaniesResponseBody() {
        }
        
        public GetByCompaniesResponseBody(string GetByCompaniesResult) {
            this.GetByCompaniesResult = GetByCompaniesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByCompanyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByCompany", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.ProjectService.GetByCompanyRequestBody Body;
        
        public GetByCompanyRequest() {
        }
        
        public GetByCompanyRequest(SocialRequirements.ProjectService.GetByCompanyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByCompanyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long companyId;
        
        public GetByCompanyRequestBody() {
        }
        
        public GetByCompanyRequestBody(long companyId) {
            this.companyId = companyId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByCompanyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByCompanyResponse", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.ProjectService.GetByCompanyResponseBody Body;
        
        public GetByCompanyResponse() {
        }
        
        public GetByCompanyResponse(SocialRequirements.ProjectService.GetByCompanyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByCompanyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetByCompanyResult;
        
        public GetByCompanyResponseBody() {
        }
        
        public GetByCompanyResponseBody(string GetByCompanyResult) {
            this.GetByCompanyResult = GetByCompanyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProjectSoapChannel : SocialRequirements.ProjectService.ProjectSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProjectSoapClient : System.ServiceModel.ClientBase<SocialRequirements.ProjectService.ProjectSoap>, SocialRequirements.ProjectService.ProjectSoap {
        
        public ProjectSoapClient() {
        }
        
        public ProjectSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProjectSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocialRequirements.ProjectService.AddProjectResponse SocialRequirements.ProjectService.ProjectSoap.AddProject(SocialRequirements.ProjectService.AddProjectRequest request) {
            return base.Channel.AddProject(request);
        }
        
        public void AddProject(string name, string description, long companyId, string encUsername) {
            SocialRequirements.ProjectService.AddProjectRequest inValue = new SocialRequirements.ProjectService.AddProjectRequest();
            inValue.Body = new SocialRequirements.ProjectService.AddProjectRequestBody();
            inValue.Body.name = name;
            inValue.Body.description = description;
            inValue.Body.companyId = companyId;
            inValue.Body.encUsername = encUsername;
            SocialRequirements.ProjectService.AddProjectResponse retVal = ((SocialRequirements.ProjectService.ProjectSoap)(this)).AddProject(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SocialRequirements.ProjectService.AddProjectResponse> SocialRequirements.ProjectService.ProjectSoap.AddProjectAsync(SocialRequirements.ProjectService.AddProjectRequest request) {
            return base.Channel.AddProjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<SocialRequirements.ProjectService.AddProjectResponse> AddProjectAsync(string name, string description, long companyId, string encUsername) {
            SocialRequirements.ProjectService.AddProjectRequest inValue = new SocialRequirements.ProjectService.AddProjectRequest();
            inValue.Body = new SocialRequirements.ProjectService.AddProjectRequestBody();
            inValue.Body.name = name;
            inValue.Body.description = description;
            inValue.Body.companyId = companyId;
            inValue.Body.encUsername = encUsername;
            return ((SocialRequirements.ProjectService.ProjectSoap)(this)).AddProjectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocialRequirements.ProjectService.GetByCompaniesResponse SocialRequirements.ProjectService.ProjectSoap.GetByCompanies(SocialRequirements.ProjectService.GetByCompaniesRequest request) {
            return base.Channel.GetByCompanies(request);
        }
        
        public string GetByCompanies(SocialRequirements.ProjectService.ArrayOfLong companiesIdList) {
            SocialRequirements.ProjectService.GetByCompaniesRequest inValue = new SocialRequirements.ProjectService.GetByCompaniesRequest();
            inValue.Body = new SocialRequirements.ProjectService.GetByCompaniesRequestBody();
            inValue.Body.companiesIdList = companiesIdList;
            SocialRequirements.ProjectService.GetByCompaniesResponse retVal = ((SocialRequirements.ProjectService.ProjectSoap)(this)).GetByCompanies(inValue);
            return retVal.Body.GetByCompaniesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SocialRequirements.ProjectService.GetByCompaniesResponse> SocialRequirements.ProjectService.ProjectSoap.GetByCompaniesAsync(SocialRequirements.ProjectService.GetByCompaniesRequest request) {
            return base.Channel.GetByCompaniesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SocialRequirements.ProjectService.GetByCompaniesResponse> GetByCompaniesAsync(SocialRequirements.ProjectService.ArrayOfLong companiesIdList) {
            SocialRequirements.ProjectService.GetByCompaniesRequest inValue = new SocialRequirements.ProjectService.GetByCompaniesRequest();
            inValue.Body = new SocialRequirements.ProjectService.GetByCompaniesRequestBody();
            inValue.Body.companiesIdList = companiesIdList;
            return ((SocialRequirements.ProjectService.ProjectSoap)(this)).GetByCompaniesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocialRequirements.ProjectService.GetByCompanyResponse SocialRequirements.ProjectService.ProjectSoap.GetByCompany(SocialRequirements.ProjectService.GetByCompanyRequest request) {
            return base.Channel.GetByCompany(request);
        }
        
        public string GetByCompany(long companyId) {
            SocialRequirements.ProjectService.GetByCompanyRequest inValue = new SocialRequirements.ProjectService.GetByCompanyRequest();
            inValue.Body = new SocialRequirements.ProjectService.GetByCompanyRequestBody();
            inValue.Body.companyId = companyId;
            SocialRequirements.ProjectService.GetByCompanyResponse retVal = ((SocialRequirements.ProjectService.ProjectSoap)(this)).GetByCompany(inValue);
            return retVal.Body.GetByCompanyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SocialRequirements.ProjectService.GetByCompanyResponse> SocialRequirements.ProjectService.ProjectSoap.GetByCompanyAsync(SocialRequirements.ProjectService.GetByCompanyRequest request) {
            return base.Channel.GetByCompanyAsync(request);
        }
        
        public System.Threading.Tasks.Task<SocialRequirements.ProjectService.GetByCompanyResponse> GetByCompanyAsync(long companyId) {
            SocialRequirements.ProjectService.GetByCompanyRequest inValue = new SocialRequirements.ProjectService.GetByCompanyRequest();
            inValue.Body = new SocialRequirements.ProjectService.GetByCompanyRequestBody();
            inValue.Body.companyId = companyId;
            return ((SocialRequirements.ProjectService.ProjectSoap)(this)).GetByCompanyAsync(inValue);
        }
    }
}
