//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialRequirements.AccountService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountService.AccountSoap")]
    public interface AccountSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateNewUser", ReplyAction="*")]
        SocialRequirements.AccountService.CreateNewUserResponse CreateNewUser(SocialRequirements.AccountService.CreateNewUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateNewUser", ReplyAction="*")]
        System.Threading.Tasks.Task<SocialRequirements.AccountService.CreateNewUserResponse> CreateNewUserAsync(SocialRequirements.AccountService.CreateNewUserRequest request);
        
        // CODEGEN: Generating message contract since element name encUsername from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidatePassword", ReplyAction="*")]
        SocialRequirements.AccountService.ValidatePasswordResponse ValidatePassword(SocialRequirements.AccountService.ValidatePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidatePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<SocialRequirements.AccountService.ValidatePasswordResponse> ValidatePasswordAsync(SocialRequirements.AccountService.ValidatePasswordRequest request);
        
        // CODEGEN: Generating message contract since element name encUsername from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserCompanies", ReplyAction="*")]
        SocialRequirements.AccountService.GetUserCompaniesResponse GetUserCompanies(SocialRequirements.AccountService.GetUserCompaniesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserCompanies", ReplyAction="*")]
        System.Threading.Tasks.Task<SocialRequirements.AccountService.GetUserCompaniesResponse> GetUserCompaniesAsync(SocialRequirements.AccountService.GetUserCompaniesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateNewUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateNewUser", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.AccountService.CreateNewUserRequestBody Body;
        
        public CreateNewUserRequest() {
        }
        
        public CreateNewUserRequest(SocialRequirements.AccountService.CreateNewUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateNewUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lastname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string encPrimaryemail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string encSecondaryemail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string encPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string birthdate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string phone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string mobilephone;
        
        public CreateNewUserRequestBody() {
        }
        
        public CreateNewUserRequestBody(string name, string lastname, string encPrimaryemail, string encSecondaryemail, string encPassword, string birthdate, string phone, string mobilephone) {
            this.name = name;
            this.lastname = lastname;
            this.encPrimaryemail = encPrimaryemail;
            this.encSecondaryemail = encSecondaryemail;
            this.encPassword = encPassword;
            this.birthdate = birthdate;
            this.phone = phone;
            this.mobilephone = mobilephone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateNewUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateNewUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.AccountService.CreateNewUserResponseBody Body;
        
        public CreateNewUserResponse() {
        }
        
        public CreateNewUserResponse(SocialRequirements.AccountService.CreateNewUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateNewUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CreateNewUserResult;
        
        public CreateNewUserResponseBody() {
        }
        
        public CreateNewUserResponseBody(int CreateNewUserResult) {
            this.CreateNewUserResult = CreateNewUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidatePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidatePassword", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.AccountService.ValidatePasswordRequestBody Body;
        
        public ValidatePasswordRequest() {
        }
        
        public ValidatePasswordRequest(SocialRequirements.AccountService.ValidatePasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidatePasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string encUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string encPassword;
        
        public ValidatePasswordRequestBody() {
        }
        
        public ValidatePasswordRequestBody(string encUsername, string encPassword) {
            this.encUsername = encUsername;
            this.encPassword = encPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidatePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidatePasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.AccountService.ValidatePasswordResponseBody Body;
        
        public ValidatePasswordResponse() {
        }
        
        public ValidatePasswordResponse(SocialRequirements.AccountService.ValidatePasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidatePasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ValidatePasswordResult;
        
        public ValidatePasswordResponseBody() {
        }
        
        public ValidatePasswordResponseBody(bool ValidatePasswordResult) {
            this.ValidatePasswordResult = ValidatePasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserCompaniesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserCompanies", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.AccountService.GetUserCompaniesRequestBody Body;
        
        public GetUserCompaniesRequest() {
        }
        
        public GetUserCompaniesRequest(SocialRequirements.AccountService.GetUserCompaniesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserCompaniesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string encUsername;
        
        public GetUserCompaniesRequestBody() {
        }
        
        public GetUserCompaniesRequestBody(string encUsername) {
            this.encUsername = encUsername;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserCompaniesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserCompaniesResponse", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.AccountService.GetUserCompaniesResponseBody Body;
        
        public GetUserCompaniesResponse() {
        }
        
        public GetUserCompaniesResponse(SocialRequirements.AccountService.GetUserCompaniesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserCompaniesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserCompaniesResult;
        
        public GetUserCompaniesResponseBody() {
        }
        
        public GetUserCompaniesResponseBody(string GetUserCompaniesResult) {
            this.GetUserCompaniesResult = GetUserCompaniesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccountSoapChannel : SocialRequirements.AccountService.AccountSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountSoapClient : System.ServiceModel.ClientBase<SocialRequirements.AccountService.AccountSoap>, SocialRequirements.AccountService.AccountSoap {
        
        public AccountSoapClient() {
        }
        
        public AccountSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocialRequirements.AccountService.CreateNewUserResponse SocialRequirements.AccountService.AccountSoap.CreateNewUser(SocialRequirements.AccountService.CreateNewUserRequest request) {
            return base.Channel.CreateNewUser(request);
        }
        
        public int CreateNewUser(string name, string lastname, string encPrimaryemail, string encSecondaryemail, string encPassword, string birthdate, string phone, string mobilephone) {
            SocialRequirements.AccountService.CreateNewUserRequest inValue = new SocialRequirements.AccountService.CreateNewUserRequest();
            inValue.Body = new SocialRequirements.AccountService.CreateNewUserRequestBody();
            inValue.Body.name = name;
            inValue.Body.lastname = lastname;
            inValue.Body.encPrimaryemail = encPrimaryemail;
            inValue.Body.encSecondaryemail = encSecondaryemail;
            inValue.Body.encPassword = encPassword;
            inValue.Body.birthdate = birthdate;
            inValue.Body.phone = phone;
            inValue.Body.mobilephone = mobilephone;
            SocialRequirements.AccountService.CreateNewUserResponse retVal = ((SocialRequirements.AccountService.AccountSoap)(this)).CreateNewUser(inValue);
            return retVal.Body.CreateNewUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SocialRequirements.AccountService.CreateNewUserResponse> SocialRequirements.AccountService.AccountSoap.CreateNewUserAsync(SocialRequirements.AccountService.CreateNewUserRequest request) {
            return base.Channel.CreateNewUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<SocialRequirements.AccountService.CreateNewUserResponse> CreateNewUserAsync(string name, string lastname, string encPrimaryemail, string encSecondaryemail, string encPassword, string birthdate, string phone, string mobilephone) {
            SocialRequirements.AccountService.CreateNewUserRequest inValue = new SocialRequirements.AccountService.CreateNewUserRequest();
            inValue.Body = new SocialRequirements.AccountService.CreateNewUserRequestBody();
            inValue.Body.name = name;
            inValue.Body.lastname = lastname;
            inValue.Body.encPrimaryemail = encPrimaryemail;
            inValue.Body.encSecondaryemail = encSecondaryemail;
            inValue.Body.encPassword = encPassword;
            inValue.Body.birthdate = birthdate;
            inValue.Body.phone = phone;
            inValue.Body.mobilephone = mobilephone;
            return ((SocialRequirements.AccountService.AccountSoap)(this)).CreateNewUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocialRequirements.AccountService.ValidatePasswordResponse SocialRequirements.AccountService.AccountSoap.ValidatePassword(SocialRequirements.AccountService.ValidatePasswordRequest request) {
            return base.Channel.ValidatePassword(request);
        }
        
        public bool ValidatePassword(string encUsername, string encPassword) {
            SocialRequirements.AccountService.ValidatePasswordRequest inValue = new SocialRequirements.AccountService.ValidatePasswordRequest();
            inValue.Body = new SocialRequirements.AccountService.ValidatePasswordRequestBody();
            inValue.Body.encUsername = encUsername;
            inValue.Body.encPassword = encPassword;
            SocialRequirements.AccountService.ValidatePasswordResponse retVal = ((SocialRequirements.AccountService.AccountSoap)(this)).ValidatePassword(inValue);
            return retVal.Body.ValidatePasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SocialRequirements.AccountService.ValidatePasswordResponse> SocialRequirements.AccountService.AccountSoap.ValidatePasswordAsync(SocialRequirements.AccountService.ValidatePasswordRequest request) {
            return base.Channel.ValidatePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<SocialRequirements.AccountService.ValidatePasswordResponse> ValidatePasswordAsync(string encUsername, string encPassword) {
            SocialRequirements.AccountService.ValidatePasswordRequest inValue = new SocialRequirements.AccountService.ValidatePasswordRequest();
            inValue.Body = new SocialRequirements.AccountService.ValidatePasswordRequestBody();
            inValue.Body.encUsername = encUsername;
            inValue.Body.encPassword = encPassword;
            return ((SocialRequirements.AccountService.AccountSoap)(this)).ValidatePasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocialRequirements.AccountService.GetUserCompaniesResponse SocialRequirements.AccountService.AccountSoap.GetUserCompanies(SocialRequirements.AccountService.GetUserCompaniesRequest request) {
            return base.Channel.GetUserCompanies(request);
        }
        
        public string GetUserCompanies(string encUsername) {
            SocialRequirements.AccountService.GetUserCompaniesRequest inValue = new SocialRequirements.AccountService.GetUserCompaniesRequest();
            inValue.Body = new SocialRequirements.AccountService.GetUserCompaniesRequestBody();
            inValue.Body.encUsername = encUsername;
            SocialRequirements.AccountService.GetUserCompaniesResponse retVal = ((SocialRequirements.AccountService.AccountSoap)(this)).GetUserCompanies(inValue);
            return retVal.Body.GetUserCompaniesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SocialRequirements.AccountService.GetUserCompaniesResponse> SocialRequirements.AccountService.AccountSoap.GetUserCompaniesAsync(SocialRequirements.AccountService.GetUserCompaniesRequest request) {
            return base.Channel.GetUserCompaniesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SocialRequirements.AccountService.GetUserCompaniesResponse> GetUserCompaniesAsync(string encUsername) {
            SocialRequirements.AccountService.GetUserCompaniesRequest inValue = new SocialRequirements.AccountService.GetUserCompaniesRequest();
            inValue.Body = new SocialRequirements.AccountService.GetUserCompaniesRequestBody();
            inValue.Body.encUsername = encUsername;
            return ((SocialRequirements.AccountService.AccountSoap)(this)).GetUserCompaniesAsync(inValue);
        }
    }
}
