//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.Threading.Tasks;

namespace SocialRequirements.AccountService {
    
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(ConfigurationName="AccountService.AccountSoap")]
    public interface AccountSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [OperationContract(Action="http://tempuri.org/CreateNewUser", ReplyAction="*")]
        CreateNewUserResponse CreateNewUser(CreateNewUserRequest request);
        
        [OperationContract(Action="http://tempuri.org/CreateNewUser", ReplyAction="*")]
        Task<CreateNewUserResponse> CreateNewUserAsync(CreateNewUserRequest request);
        
        // CODEGEN: Generating message contract since element name encUsername from namespace http://tempuri.org/ is not marked nillable
        [OperationContract(Action="http://tempuri.org/ValidatePassword", ReplyAction="*")]
        ValidatePasswordResponse ValidatePassword(ValidatePasswordRequest request);
        
        [OperationContract(Action="http://tempuri.org/ValidatePassword", ReplyAction="*")]
        Task<ValidatePasswordResponse> ValidatePasswordAsync(ValidatePasswordRequest request);
        
        // CODEGEN: Generating message contract since element name encUsername from namespace http://tempuri.org/ is not marked nillable
        [OperationContract(Action="http://tempuri.org/GetUserCompanies", ReplyAction="*")]
        GetUserCompaniesResponse GetUserCompanies(GetUserCompaniesRequest request);
        
        [OperationContract(Action="http://tempuri.org/GetUserCompanies", ReplyAction="*")]
        Task<GetUserCompaniesResponse> GetUserCompaniesAsync(GetUserCompaniesRequest request);
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(IsWrapped=false)]
    public partial class CreateNewUserRequest {
        
        [MessageBodyMember(Name="CreateNewUser", Namespace="http://tempuri.org/", Order=0)]
        public CreateNewUserRequestBody Body;
        
        public CreateNewUserRequest() {
        }
        
        public CreateNewUserRequest(CreateNewUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://tempuri.org/")]
    public partial class CreateNewUserRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string lastname;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string encPrimaryemail;
        
        [DataMember(EmitDefaultValue=false, Order=3)]
        public string encSecondaryemail;
        
        [DataMember(EmitDefaultValue=false, Order=4)]
        public string encPassword;
        
        [DataMember(EmitDefaultValue=false, Order=5)]
        public string birthdate;
        
        [DataMember(EmitDefaultValue=false, Order=6)]
        public string phone;
        
        [DataMember(EmitDefaultValue=false, Order=7)]
        public string mobilephone;
        
        public CreateNewUserRequestBody() {
        }
        
        public CreateNewUserRequestBody(string name, string lastname, string encPrimaryemail, string encSecondaryemail, string encPassword, string birthdate, string phone, string mobilephone) {
            this.name = name;
            this.lastname = lastname;
            this.encPrimaryemail = encPrimaryemail;
            this.encSecondaryemail = encSecondaryemail;
            this.encPassword = encPassword;
            this.birthdate = birthdate;
            this.phone = phone;
            this.mobilephone = mobilephone;
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(IsWrapped=false)]
    public partial class CreateNewUserResponse {
        
        [MessageBodyMember(Name="CreateNewUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public CreateNewUserResponseBody Body;
        
        public CreateNewUserResponse() {
        }
        
        public CreateNewUserResponse(CreateNewUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://tempuri.org/")]
    public partial class CreateNewUserResponseBody {
        
        [DataMember(Order=0)]
        public int CreateNewUserResult;
        
        public CreateNewUserResponseBody() {
        }
        
        public CreateNewUserResponseBody(int CreateNewUserResult) {
            this.CreateNewUserResult = CreateNewUserResult;
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(IsWrapped=false)]
    public partial class ValidatePasswordRequest {
        
        [MessageBodyMember(Name="ValidatePassword", Namespace="http://tempuri.org/", Order=0)]
        public ValidatePasswordRequestBody Body;
        
        public ValidatePasswordRequest() {
        }
        
        public ValidatePasswordRequest(ValidatePasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://tempuri.org/")]
    public partial class ValidatePasswordRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string encUsername;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string encPassword;
        
        public ValidatePasswordRequestBody() {
        }
        
        public ValidatePasswordRequestBody(string encUsername, string encPassword) {
            this.encUsername = encUsername;
            this.encPassword = encPassword;
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(IsWrapped=false)]
    public partial class ValidatePasswordResponse {
        
        [MessageBodyMember(Name="ValidatePasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public ValidatePasswordResponseBody Body;
        
        public ValidatePasswordResponse() {
        }
        
        public ValidatePasswordResponse(ValidatePasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://tempuri.org/")]
    public partial class ValidatePasswordResponseBody {
        
        [DataMember(Order=0)]
        public bool ValidatePasswordResult;
        
        public ValidatePasswordResponseBody() {
        }
        
        public ValidatePasswordResponseBody(bool ValidatePasswordResult) {
            this.ValidatePasswordResult = ValidatePasswordResult;
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(IsWrapped=false)]
    public partial class GetUserCompaniesRequest {
        
        [MessageBodyMember(Name="GetUserCompanies", Namespace="http://tempuri.org/", Order=0)]
        public GetUserCompaniesRequestBody Body;
        
        public GetUserCompaniesRequest() {
        }
        
        public GetUserCompaniesRequest(GetUserCompaniesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://tempuri.org/")]
    public partial class GetUserCompaniesRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string encUsername;
        
        public GetUserCompaniesRequestBody() {
        }
        
        public GetUserCompaniesRequestBody(string encUsername) {
            this.encUsername = encUsername;
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(IsWrapped=false)]
    public partial class GetUserCompaniesResponse {
        
        [MessageBodyMember(Name="GetUserCompaniesResponse", Namespace="http://tempuri.org/", Order=0)]
        public GetUserCompaniesResponseBody Body;
        
        public GetUserCompaniesResponse() {
        }
        
        public GetUserCompaniesResponse(GetUserCompaniesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://tempuri.org/")]
    public partial class GetUserCompaniesResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string GetUserCompaniesResult;
        
        public GetUserCompaniesResponseBody() {
        }
        
        public GetUserCompaniesResponseBody(string GetUserCompaniesResult) {
            this.GetUserCompaniesResult = GetUserCompaniesResult;
        }
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface AccountSoapChannel : AccountSoap, IClientChannel {
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public partial class AccountSoapClient : ClientBase<AccountSoap>, AccountSoap {
        
        public AccountSoapClient() {
        }
        
        public AccountSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountSoapClient(string endpointConfigurationName, EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountSoapClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        CreateNewUserResponse AccountSoap.CreateNewUser(CreateNewUserRequest request) {
            return base.Channel.CreateNewUser(request);
        }
        
        public int CreateNewUser(string name, string lastname, string encPrimaryemail, string encSecondaryemail, string encPassword, string birthdate, string phone, string mobilephone) {
            CreateNewUserRequest inValue = new CreateNewUserRequest();
            inValue.Body = new CreateNewUserRequestBody();
            inValue.Body.name = name;
            inValue.Body.lastname = lastname;
            inValue.Body.encPrimaryemail = encPrimaryemail;
            inValue.Body.encSecondaryemail = encSecondaryemail;
            inValue.Body.encPassword = encPassword;
            inValue.Body.birthdate = birthdate;
            inValue.Body.phone = phone;
            inValue.Body.mobilephone = mobilephone;
            CreateNewUserResponse retVal = ((AccountSoap)(this)).CreateNewUser(inValue);
            return retVal.Body.CreateNewUserResult;
        }
        
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        Task<CreateNewUserResponse> AccountSoap.CreateNewUserAsync(CreateNewUserRequest request) {
            return base.Channel.CreateNewUserAsync(request);
        }
        
        public Task<CreateNewUserResponse> CreateNewUserAsync(string name, string lastname, string encPrimaryemail, string encSecondaryemail, string encPassword, string birthdate, string phone, string mobilephone) {
            CreateNewUserRequest inValue = new CreateNewUserRequest();
            inValue.Body = new CreateNewUserRequestBody();
            inValue.Body.name = name;
            inValue.Body.lastname = lastname;
            inValue.Body.encPrimaryemail = encPrimaryemail;
            inValue.Body.encSecondaryemail = encSecondaryemail;
            inValue.Body.encPassword = encPassword;
            inValue.Body.birthdate = birthdate;
            inValue.Body.phone = phone;
            inValue.Body.mobilephone = mobilephone;
            return ((AccountSoap)(this)).CreateNewUserAsync(inValue);
        }
        
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        ValidatePasswordResponse AccountSoap.ValidatePassword(ValidatePasswordRequest request) {
            return base.Channel.ValidatePassword(request);
        }
        
        public bool ValidatePassword(string encUsername, string encPassword) {
            ValidatePasswordRequest inValue = new ValidatePasswordRequest();
            inValue.Body = new ValidatePasswordRequestBody();
            inValue.Body.encUsername = encUsername;
            inValue.Body.encPassword = encPassword;
            ValidatePasswordResponse retVal = ((AccountSoap)(this)).ValidatePassword(inValue);
            return retVal.Body.ValidatePasswordResult;
        }
        
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        Task<ValidatePasswordResponse> AccountSoap.ValidatePasswordAsync(ValidatePasswordRequest request) {
            return base.Channel.ValidatePasswordAsync(request);
        }
        
        public Task<ValidatePasswordResponse> ValidatePasswordAsync(string encUsername, string encPassword) {
            ValidatePasswordRequest inValue = new ValidatePasswordRequest();
            inValue.Body = new ValidatePasswordRequestBody();
            inValue.Body.encUsername = encUsername;
            inValue.Body.encPassword = encPassword;
            return ((AccountSoap)(this)).ValidatePasswordAsync(inValue);
        }
        
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        GetUserCompaniesResponse AccountSoap.GetUserCompanies(GetUserCompaniesRequest request) {
            return base.Channel.GetUserCompanies(request);
        }
        
        public string GetUserCompanies(string encUsername) {
            GetUserCompaniesRequest inValue = new GetUserCompaniesRequest();
            inValue.Body = new GetUserCompaniesRequestBody();
            inValue.Body.encUsername = encUsername;
            GetUserCompaniesResponse retVal = ((AccountSoap)(this)).GetUserCompanies(inValue);
            return retVal.Body.GetUserCompaniesResult;
        }
        
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        Task<GetUserCompaniesResponse> AccountSoap.GetUserCompaniesAsync(GetUserCompaniesRequest request) {
            return base.Channel.GetUserCompaniesAsync(request);
        }
        
        public Task<GetUserCompaniesResponse> GetUserCompaniesAsync(string encUsername) {
            GetUserCompaniesRequest inValue = new GetUserCompaniesRequest();
            inValue.Body = new GetUserCompaniesRequestBody();
            inValue.Body.encUsername = encUsername;
            return ((AccountSoap)(this)).GetUserCompaniesAsync(inValue);
        }
    }
}
