//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialRequirements.RequirementService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RequirementService.RequirementSoap")]
    public interface RequirementSoap {
        
        // CODEGEN: Generating message contract since element name title from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddRequirement", ReplyAction="*")]
        SocialRequirements.RequirementService.AddRequirementResponse AddRequirement(SocialRequirements.RequirementService.AddRequirementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddRequirement", ReplyAction="*")]
        System.Threading.Tasks.Task<SocialRequirements.RequirementService.AddRequirementResponse> AddRequirementAsync(SocialRequirements.RequirementService.AddRequirementRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequirementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRequirement", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.RequirementService.AddRequirementRequestBody Body;
        
        public AddRequirementRequest() {
        }
        
        public AddRequirementRequest(SocialRequirements.RequirementService.AddRequirementRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequirementRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long companyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long projectId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string encUsername;
        
        public AddRequirementRequestBody() {
        }
        
        public AddRequirementRequestBody(string title, string description, long companyId, long projectId, string encUsername) {
            this.title = title;
            this.description = description;
            this.companyId = companyId;
            this.projectId = projectId;
            this.encUsername = encUsername;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequirementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRequirementResponse", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.RequirementService.AddRequirementResponseBody Body;
        
        public AddRequirementResponse() {
        }
        
        public AddRequirementResponse(SocialRequirements.RequirementService.AddRequirementResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddRequirementResponseBody {
        
        public AddRequirementResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RequirementSoapChannel : SocialRequirements.RequirementService.RequirementSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RequirementSoapClient : System.ServiceModel.ClientBase<SocialRequirements.RequirementService.RequirementSoap>, SocialRequirements.RequirementService.RequirementSoap {
        
        public RequirementSoapClient() {
        }
        
        public RequirementSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RequirementSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequirementSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequirementSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocialRequirements.RequirementService.AddRequirementResponse SocialRequirements.RequirementService.RequirementSoap.AddRequirement(SocialRequirements.RequirementService.AddRequirementRequest request) {
            return base.Channel.AddRequirement(request);
        }
        
        public void AddRequirement(string title, string description, long companyId, long projectId, string encUsername) {
            SocialRequirements.RequirementService.AddRequirementRequest inValue = new SocialRequirements.RequirementService.AddRequirementRequest();
            inValue.Body = new SocialRequirements.RequirementService.AddRequirementRequestBody();
            inValue.Body.title = title;
            inValue.Body.description = description;
            inValue.Body.companyId = companyId;
            inValue.Body.projectId = projectId;
            inValue.Body.encUsername = encUsername;
            SocialRequirements.RequirementService.AddRequirementResponse retVal = ((SocialRequirements.RequirementService.RequirementSoap)(this)).AddRequirement(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SocialRequirements.RequirementService.AddRequirementResponse> SocialRequirements.RequirementService.RequirementSoap.AddRequirementAsync(SocialRequirements.RequirementService.AddRequirementRequest request) {
            return base.Channel.AddRequirementAsync(request);
        }
        
        public System.Threading.Tasks.Task<SocialRequirements.RequirementService.AddRequirementResponse> AddRequirementAsync(string title, string description, long companyId, long projectId, string encUsername) {
            SocialRequirements.RequirementService.AddRequirementRequest inValue = new SocialRequirements.RequirementService.AddRequirementRequest();
            inValue.Body = new SocialRequirements.RequirementService.AddRequirementRequestBody();
            inValue.Body.title = title;
            inValue.Body.description = description;
            inValue.Body.companyId = companyId;
            inValue.Body.projectId = projectId;
            inValue.Body.encUsername = encUsername;
            return ((SocialRequirements.RequirementService.RequirementSoap)(this)).AddRequirementAsync(inValue);
        }
    }
}
