//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialRequirements.RequirementService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RequirementService.RequirementSoap")]
    public interface RequirementSoap {
        
        // CODEGEN: Generating message contract since element name title from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddRequirement", ReplyAction="*")]
        SocialRequirements.RequirementService.AddRequirementResponse AddRequirement(SocialRequirements.RequirementService.AddRequirementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddRequirement", ReplyAction="*")]
        System.Threading.Tasks.Task<SocialRequirements.RequirementService.AddRequirementResponse> AddRequirementAsync(SocialRequirements.RequirementService.AddRequirementRequest request);
        
        // CODEGEN: Generating message contract since element name encUsername from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LikeRequirement", ReplyAction="*")]
        SocialRequirements.RequirementService.LikeRequirementResponse LikeRequirement(SocialRequirements.RequirementService.LikeRequirementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LikeRequirement", ReplyAction="*")]
        System.Threading.Tasks.Task<SocialRequirements.RequirementService.LikeRequirementResponse> LikeRequirementAsync(SocialRequirements.RequirementService.LikeRequirementRequest request);
        
        // CODEGEN: Generating message contract since element name encUsername from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DislikeRequirement", ReplyAction="*")]
        SocialRequirements.RequirementService.DislikeRequirementResponse DislikeRequirement(SocialRequirements.RequirementService.DislikeRequirementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DislikeRequirement", ReplyAction="*")]
        System.Threading.Tasks.Task<SocialRequirements.RequirementService.DislikeRequirementResponse> DislikeRequirementAsync(SocialRequirements.RequirementService.DislikeRequirementRequest request);
        
        // CODEGEN: Generating message contract since element name encUsername from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CommentOnRequirement", ReplyAction="*")]
        SocialRequirements.RequirementService.CommentOnRequirementResponse CommentOnRequirement(SocialRequirements.RequirementService.CommentOnRequirementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CommentOnRequirement", ReplyAction="*")]
        System.Threading.Tasks.Task<SocialRequirements.RequirementService.CommentOnRequirementResponse> CommentOnRequirementAsync(SocialRequirements.RequirementService.CommentOnRequirementRequest request);
        
        // CODEGEN: Generating message contract since element name encUsername from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRequirementsList", ReplyAction="*")]
        SocialRequirements.RequirementService.GetRequirementsListResponse GetRequirementsList(SocialRequirements.RequirementService.GetRequirementsListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRequirementsList", ReplyAction="*")]
        System.Threading.Tasks.Task<SocialRequirements.RequirementService.GetRequirementsListResponse> GetRequirementsListAsync(SocialRequirements.RequirementService.GetRequirementsListRequest request);
        
        // CODEGEN: Generating message contract since element name GetRequirementResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRequirement", ReplyAction="*")]
        SocialRequirements.RequirementService.GetRequirementResponse GetRequirement(SocialRequirements.RequirementService.GetRequirementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRequirement", ReplyAction="*")]
        System.Threading.Tasks.Task<SocialRequirements.RequirementService.GetRequirementResponse> GetRequirementAsync(SocialRequirements.RequirementService.GetRequirementRequest request);
        
        // CODEGEN: Generating message contract since element name encUsername from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ApproveRequirement", ReplyAction="*")]
        SocialRequirements.RequirementService.ApproveRequirementResponse ApproveRequirement(SocialRequirements.RequirementService.ApproveRequirementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ApproveRequirement", ReplyAction="*")]
        System.Threading.Tasks.Task<SocialRequirements.RequirementService.ApproveRequirementResponse> ApproveRequirementAsync(SocialRequirements.RequirementService.ApproveRequirementRequest request);
        
        // CODEGEN: Generating message contract since element name encUsername from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RejectRequirement", ReplyAction="*")]
        SocialRequirements.RequirementService.RejectRequirementResponse RejectRequirement(SocialRequirements.RequirementService.RejectRequirementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RejectRequirement", ReplyAction="*")]
        System.Threading.Tasks.Task<SocialRequirements.RequirementService.RejectRequirementResponse> RejectRequirementAsync(SocialRequirements.RequirementService.RejectRequirementRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequirementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRequirement", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.RequirementService.AddRequirementRequestBody Body;
        
        public AddRequirementRequest() {
        }
        
        public AddRequirementRequest(SocialRequirements.RequirementService.AddRequirementRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequirementRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long companyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long projectId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string encUsername;
        
        public AddRequirementRequestBody() {
        }
        
        public AddRequirementRequestBody(string title, string description, long companyId, long projectId, string encUsername) {
            this.title = title;
            this.description = description;
            this.companyId = companyId;
            this.projectId = projectId;
            this.encUsername = encUsername;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequirementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRequirementResponse", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.RequirementService.AddRequirementResponseBody Body;
        
        public AddRequirementResponse() {
        }
        
        public AddRequirementResponse(SocialRequirements.RequirementService.AddRequirementResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddRequirementResponseBody {
        
        public AddRequirementResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LikeRequirementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LikeRequirement", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.RequirementService.LikeRequirementRequestBody Body;
        
        public LikeRequirementRequest() {
        }
        
        public LikeRequirementRequest(SocialRequirements.RequirementService.LikeRequirementRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LikeRequirementRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long companyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long projectId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long requirementId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string encUsername;
        
        public LikeRequirementRequestBody() {
        }
        
        public LikeRequirementRequestBody(long companyId, long projectId, long requirementId, string encUsername) {
            this.companyId = companyId;
            this.projectId = projectId;
            this.requirementId = requirementId;
            this.encUsername = encUsername;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LikeRequirementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LikeRequirementResponse", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.RequirementService.LikeRequirementResponseBody Body;
        
        public LikeRequirementResponse() {
        }
        
        public LikeRequirementResponse(SocialRequirements.RequirementService.LikeRequirementResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LikeRequirementResponseBody {
        
        public LikeRequirementResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DislikeRequirementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DislikeRequirement", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.RequirementService.DislikeRequirementRequestBody Body;
        
        public DislikeRequirementRequest() {
        }
        
        public DislikeRequirementRequest(SocialRequirements.RequirementService.DislikeRequirementRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DislikeRequirementRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long companyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long projectId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long requirementId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string encUsername;
        
        public DislikeRequirementRequestBody() {
        }
        
        public DislikeRequirementRequestBody(long companyId, long projectId, long requirementId, string encUsername) {
            this.companyId = companyId;
            this.projectId = projectId;
            this.requirementId = requirementId;
            this.encUsername = encUsername;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DislikeRequirementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DislikeRequirementResponse", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.RequirementService.DislikeRequirementResponseBody Body;
        
        public DislikeRequirementResponse() {
        }
        
        public DislikeRequirementResponse(SocialRequirements.RequirementService.DislikeRequirementResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DislikeRequirementResponseBody {
        
        public DislikeRequirementResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CommentOnRequirementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CommentOnRequirement", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.RequirementService.CommentOnRequirementRequestBody Body;
        
        public CommentOnRequirementRequest() {
        }
        
        public CommentOnRequirementRequest(SocialRequirements.RequirementService.CommentOnRequirementRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CommentOnRequirementRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long requirementId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string encUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string comment;
        
        public CommentOnRequirementRequestBody() {
        }
        
        public CommentOnRequirementRequestBody(long requirementId, string encUsername, string comment) {
            this.requirementId = requirementId;
            this.encUsername = encUsername;
            this.comment = comment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CommentOnRequirementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CommentOnRequirementResponse", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.RequirementService.CommentOnRequirementResponseBody Body;
        
        public CommentOnRequirementResponse() {
        }
        
        public CommentOnRequirementResponse(SocialRequirements.RequirementService.CommentOnRequirementResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CommentOnRequirementResponseBody {
        
        public CommentOnRequirementResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequirementsListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRequirementsList", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.RequirementService.GetRequirementsListRequestBody Body;
        
        public GetRequirementsListRequest() {
        }
        
        public GetRequirementsListRequest(SocialRequirements.RequirementService.GetRequirementsListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRequirementsListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string encUsername;
        
        public GetRequirementsListRequestBody() {
        }
        
        public GetRequirementsListRequestBody(string encUsername) {
            this.encUsername = encUsername;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequirementsListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRequirementsListResponse", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.RequirementService.GetRequirementsListResponseBody Body;
        
        public GetRequirementsListResponse() {
        }
        
        public GetRequirementsListResponse(SocialRequirements.RequirementService.GetRequirementsListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRequirementsListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetRequirementsListResult;
        
        public GetRequirementsListResponseBody() {
        }
        
        public GetRequirementsListResponseBody(string GetRequirementsListResult) {
            this.GetRequirementsListResult = GetRequirementsListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequirementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRequirement", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.RequirementService.GetRequirementRequestBody Body;
        
        public GetRequirementRequest() {
        }
        
        public GetRequirementRequest(SocialRequirements.RequirementService.GetRequirementRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRequirementRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long companyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long projectId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long requirementId;
        
        public GetRequirementRequestBody() {
        }
        
        public GetRequirementRequestBody(long companyId, long projectId, long requirementId) {
            this.companyId = companyId;
            this.projectId = projectId;
            this.requirementId = requirementId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequirementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRequirementResponse", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.RequirementService.GetRequirementResponseBody Body;
        
        public GetRequirementResponse() {
        }
        
        public GetRequirementResponse(SocialRequirements.RequirementService.GetRequirementResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRequirementResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetRequirementResult;
        
        public GetRequirementResponseBody() {
        }
        
        public GetRequirementResponseBody(string GetRequirementResult) {
            this.GetRequirementResult = GetRequirementResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ApproveRequirementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ApproveRequirement", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.RequirementService.ApproveRequirementRequestBody Body;
        
        public ApproveRequirementRequest() {
        }
        
        public ApproveRequirementRequest(SocialRequirements.RequirementService.ApproveRequirementRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ApproveRequirementRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long companyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long projectId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long requirementId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string encUsername;
        
        public ApproveRequirementRequestBody() {
        }
        
        public ApproveRequirementRequestBody(long companyId, long projectId, long requirementId, string encUsername) {
            this.companyId = companyId;
            this.projectId = projectId;
            this.requirementId = requirementId;
            this.encUsername = encUsername;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ApproveRequirementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ApproveRequirementResponse", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.RequirementService.ApproveRequirementResponseBody Body;
        
        public ApproveRequirementResponse() {
        }
        
        public ApproveRequirementResponse(SocialRequirements.RequirementService.ApproveRequirementResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ApproveRequirementResponseBody {
        
        public ApproveRequirementResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RejectRequirementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RejectRequirement", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.RequirementService.RejectRequirementRequestBody Body;
        
        public RejectRequirementRequest() {
        }
        
        public RejectRequirementRequest(SocialRequirements.RequirementService.RejectRequirementRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RejectRequirementRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long companyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long projectId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long requirementId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string encUsername;
        
        public RejectRequirementRequestBody() {
        }
        
        public RejectRequirementRequestBody(long companyId, long projectId, long requirementId, string encUsername) {
            this.companyId = companyId;
            this.projectId = projectId;
            this.requirementId = requirementId;
            this.encUsername = encUsername;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RejectRequirementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RejectRequirementResponse", Namespace="http://tempuri.org/", Order=0)]
        public SocialRequirements.RequirementService.RejectRequirementResponseBody Body;
        
        public RejectRequirementResponse() {
        }
        
        public RejectRequirementResponse(SocialRequirements.RequirementService.RejectRequirementResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RejectRequirementResponseBody {
        
        public RejectRequirementResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RequirementSoapChannel : SocialRequirements.RequirementService.RequirementSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RequirementSoapClient : System.ServiceModel.ClientBase<SocialRequirements.RequirementService.RequirementSoap>, SocialRequirements.RequirementService.RequirementSoap {
        
        public RequirementSoapClient() {
        }
        
        public RequirementSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RequirementSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequirementSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequirementSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocialRequirements.RequirementService.AddRequirementResponse SocialRequirements.RequirementService.RequirementSoap.AddRequirement(SocialRequirements.RequirementService.AddRequirementRequest request) {
            return base.Channel.AddRequirement(request);
        }
        
        public void AddRequirement(string title, string description, long companyId, long projectId, string encUsername) {
            SocialRequirements.RequirementService.AddRequirementRequest inValue = new SocialRequirements.RequirementService.AddRequirementRequest();
            inValue.Body = new SocialRequirements.RequirementService.AddRequirementRequestBody();
            inValue.Body.title = title;
            inValue.Body.description = description;
            inValue.Body.companyId = companyId;
            inValue.Body.projectId = projectId;
            inValue.Body.encUsername = encUsername;
            SocialRequirements.RequirementService.AddRequirementResponse retVal = ((SocialRequirements.RequirementService.RequirementSoap)(this)).AddRequirement(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SocialRequirements.RequirementService.AddRequirementResponse> SocialRequirements.RequirementService.RequirementSoap.AddRequirementAsync(SocialRequirements.RequirementService.AddRequirementRequest request) {
            return base.Channel.AddRequirementAsync(request);
        }
        
        public System.Threading.Tasks.Task<SocialRequirements.RequirementService.AddRequirementResponse> AddRequirementAsync(string title, string description, long companyId, long projectId, string encUsername) {
            SocialRequirements.RequirementService.AddRequirementRequest inValue = new SocialRequirements.RequirementService.AddRequirementRequest();
            inValue.Body = new SocialRequirements.RequirementService.AddRequirementRequestBody();
            inValue.Body.title = title;
            inValue.Body.description = description;
            inValue.Body.companyId = companyId;
            inValue.Body.projectId = projectId;
            inValue.Body.encUsername = encUsername;
            return ((SocialRequirements.RequirementService.RequirementSoap)(this)).AddRequirementAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocialRequirements.RequirementService.LikeRequirementResponse SocialRequirements.RequirementService.RequirementSoap.LikeRequirement(SocialRequirements.RequirementService.LikeRequirementRequest request) {
            return base.Channel.LikeRequirement(request);
        }
        
        public void LikeRequirement(long companyId, long projectId, long requirementId, string encUsername) {
            SocialRequirements.RequirementService.LikeRequirementRequest inValue = new SocialRequirements.RequirementService.LikeRequirementRequest();
            inValue.Body = new SocialRequirements.RequirementService.LikeRequirementRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.projectId = projectId;
            inValue.Body.requirementId = requirementId;
            inValue.Body.encUsername = encUsername;
            SocialRequirements.RequirementService.LikeRequirementResponse retVal = ((SocialRequirements.RequirementService.RequirementSoap)(this)).LikeRequirement(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SocialRequirements.RequirementService.LikeRequirementResponse> SocialRequirements.RequirementService.RequirementSoap.LikeRequirementAsync(SocialRequirements.RequirementService.LikeRequirementRequest request) {
            return base.Channel.LikeRequirementAsync(request);
        }
        
        public System.Threading.Tasks.Task<SocialRequirements.RequirementService.LikeRequirementResponse> LikeRequirementAsync(long companyId, long projectId, long requirementId, string encUsername) {
            SocialRequirements.RequirementService.LikeRequirementRequest inValue = new SocialRequirements.RequirementService.LikeRequirementRequest();
            inValue.Body = new SocialRequirements.RequirementService.LikeRequirementRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.projectId = projectId;
            inValue.Body.requirementId = requirementId;
            inValue.Body.encUsername = encUsername;
            return ((SocialRequirements.RequirementService.RequirementSoap)(this)).LikeRequirementAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocialRequirements.RequirementService.DislikeRequirementResponse SocialRequirements.RequirementService.RequirementSoap.DislikeRequirement(SocialRequirements.RequirementService.DislikeRequirementRequest request) {
            return base.Channel.DislikeRequirement(request);
        }
        
        public void DislikeRequirement(long companyId, long projectId, long requirementId, string encUsername) {
            SocialRequirements.RequirementService.DislikeRequirementRequest inValue = new SocialRequirements.RequirementService.DislikeRequirementRequest();
            inValue.Body = new SocialRequirements.RequirementService.DislikeRequirementRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.projectId = projectId;
            inValue.Body.requirementId = requirementId;
            inValue.Body.encUsername = encUsername;
            SocialRequirements.RequirementService.DislikeRequirementResponse retVal = ((SocialRequirements.RequirementService.RequirementSoap)(this)).DislikeRequirement(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SocialRequirements.RequirementService.DislikeRequirementResponse> SocialRequirements.RequirementService.RequirementSoap.DislikeRequirementAsync(SocialRequirements.RequirementService.DislikeRequirementRequest request) {
            return base.Channel.DislikeRequirementAsync(request);
        }
        
        public System.Threading.Tasks.Task<SocialRequirements.RequirementService.DislikeRequirementResponse> DislikeRequirementAsync(long companyId, long projectId, long requirementId, string encUsername) {
            SocialRequirements.RequirementService.DislikeRequirementRequest inValue = new SocialRequirements.RequirementService.DislikeRequirementRequest();
            inValue.Body = new SocialRequirements.RequirementService.DislikeRequirementRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.projectId = projectId;
            inValue.Body.requirementId = requirementId;
            inValue.Body.encUsername = encUsername;
            return ((SocialRequirements.RequirementService.RequirementSoap)(this)).DislikeRequirementAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocialRequirements.RequirementService.CommentOnRequirementResponse SocialRequirements.RequirementService.RequirementSoap.CommentOnRequirement(SocialRequirements.RequirementService.CommentOnRequirementRequest request) {
            return base.Channel.CommentOnRequirement(request);
        }
        
        public void CommentOnRequirement(long requirementId, string encUsername, string comment) {
            SocialRequirements.RequirementService.CommentOnRequirementRequest inValue = new SocialRequirements.RequirementService.CommentOnRequirementRequest();
            inValue.Body = new SocialRequirements.RequirementService.CommentOnRequirementRequestBody();
            inValue.Body.requirementId = requirementId;
            inValue.Body.encUsername = encUsername;
            inValue.Body.comment = comment;
            SocialRequirements.RequirementService.CommentOnRequirementResponse retVal = ((SocialRequirements.RequirementService.RequirementSoap)(this)).CommentOnRequirement(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SocialRequirements.RequirementService.CommentOnRequirementResponse> SocialRequirements.RequirementService.RequirementSoap.CommentOnRequirementAsync(SocialRequirements.RequirementService.CommentOnRequirementRequest request) {
            return base.Channel.CommentOnRequirementAsync(request);
        }
        
        public System.Threading.Tasks.Task<SocialRequirements.RequirementService.CommentOnRequirementResponse> CommentOnRequirementAsync(long requirementId, string encUsername, string comment) {
            SocialRequirements.RequirementService.CommentOnRequirementRequest inValue = new SocialRequirements.RequirementService.CommentOnRequirementRequest();
            inValue.Body = new SocialRequirements.RequirementService.CommentOnRequirementRequestBody();
            inValue.Body.requirementId = requirementId;
            inValue.Body.encUsername = encUsername;
            inValue.Body.comment = comment;
            return ((SocialRequirements.RequirementService.RequirementSoap)(this)).CommentOnRequirementAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocialRequirements.RequirementService.GetRequirementsListResponse SocialRequirements.RequirementService.RequirementSoap.GetRequirementsList(SocialRequirements.RequirementService.GetRequirementsListRequest request) {
            return base.Channel.GetRequirementsList(request);
        }
        
        public string GetRequirementsList(string encUsername) {
            SocialRequirements.RequirementService.GetRequirementsListRequest inValue = new SocialRequirements.RequirementService.GetRequirementsListRequest();
            inValue.Body = new SocialRequirements.RequirementService.GetRequirementsListRequestBody();
            inValue.Body.encUsername = encUsername;
            SocialRequirements.RequirementService.GetRequirementsListResponse retVal = ((SocialRequirements.RequirementService.RequirementSoap)(this)).GetRequirementsList(inValue);
            return retVal.Body.GetRequirementsListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SocialRequirements.RequirementService.GetRequirementsListResponse> SocialRequirements.RequirementService.RequirementSoap.GetRequirementsListAsync(SocialRequirements.RequirementService.GetRequirementsListRequest request) {
            return base.Channel.GetRequirementsListAsync(request);
        }
        
        public System.Threading.Tasks.Task<SocialRequirements.RequirementService.GetRequirementsListResponse> GetRequirementsListAsync(string encUsername) {
            SocialRequirements.RequirementService.GetRequirementsListRequest inValue = new SocialRequirements.RequirementService.GetRequirementsListRequest();
            inValue.Body = new SocialRequirements.RequirementService.GetRequirementsListRequestBody();
            inValue.Body.encUsername = encUsername;
            return ((SocialRequirements.RequirementService.RequirementSoap)(this)).GetRequirementsListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocialRequirements.RequirementService.GetRequirementResponse SocialRequirements.RequirementService.RequirementSoap.GetRequirement(SocialRequirements.RequirementService.GetRequirementRequest request) {
            return base.Channel.GetRequirement(request);
        }
        
        public string GetRequirement(long companyId, long projectId, long requirementId) {
            SocialRequirements.RequirementService.GetRequirementRequest inValue = new SocialRequirements.RequirementService.GetRequirementRequest();
            inValue.Body = new SocialRequirements.RequirementService.GetRequirementRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.projectId = projectId;
            inValue.Body.requirementId = requirementId;
            SocialRequirements.RequirementService.GetRequirementResponse retVal = ((SocialRequirements.RequirementService.RequirementSoap)(this)).GetRequirement(inValue);
            return retVal.Body.GetRequirementResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SocialRequirements.RequirementService.GetRequirementResponse> SocialRequirements.RequirementService.RequirementSoap.GetRequirementAsync(SocialRequirements.RequirementService.GetRequirementRequest request) {
            return base.Channel.GetRequirementAsync(request);
        }
        
        public System.Threading.Tasks.Task<SocialRequirements.RequirementService.GetRequirementResponse> GetRequirementAsync(long companyId, long projectId, long requirementId) {
            SocialRequirements.RequirementService.GetRequirementRequest inValue = new SocialRequirements.RequirementService.GetRequirementRequest();
            inValue.Body = new SocialRequirements.RequirementService.GetRequirementRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.projectId = projectId;
            inValue.Body.requirementId = requirementId;
            return ((SocialRequirements.RequirementService.RequirementSoap)(this)).GetRequirementAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocialRequirements.RequirementService.ApproveRequirementResponse SocialRequirements.RequirementService.RequirementSoap.ApproveRequirement(SocialRequirements.RequirementService.ApproveRequirementRequest request) {
            return base.Channel.ApproveRequirement(request);
        }
        
        public void ApproveRequirement(long companyId, long projectId, long requirementId, string encUsername) {
            SocialRequirements.RequirementService.ApproveRequirementRequest inValue = new SocialRequirements.RequirementService.ApproveRequirementRequest();
            inValue.Body = new SocialRequirements.RequirementService.ApproveRequirementRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.projectId = projectId;
            inValue.Body.requirementId = requirementId;
            inValue.Body.encUsername = encUsername;
            SocialRequirements.RequirementService.ApproveRequirementResponse retVal = ((SocialRequirements.RequirementService.RequirementSoap)(this)).ApproveRequirement(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SocialRequirements.RequirementService.ApproveRequirementResponse> SocialRequirements.RequirementService.RequirementSoap.ApproveRequirementAsync(SocialRequirements.RequirementService.ApproveRequirementRequest request) {
            return base.Channel.ApproveRequirementAsync(request);
        }
        
        public System.Threading.Tasks.Task<SocialRequirements.RequirementService.ApproveRequirementResponse> ApproveRequirementAsync(long companyId, long projectId, long requirementId, string encUsername) {
            SocialRequirements.RequirementService.ApproveRequirementRequest inValue = new SocialRequirements.RequirementService.ApproveRequirementRequest();
            inValue.Body = new SocialRequirements.RequirementService.ApproveRequirementRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.projectId = projectId;
            inValue.Body.requirementId = requirementId;
            inValue.Body.encUsername = encUsername;
            return ((SocialRequirements.RequirementService.RequirementSoap)(this)).ApproveRequirementAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocialRequirements.RequirementService.RejectRequirementResponse SocialRequirements.RequirementService.RequirementSoap.RejectRequirement(SocialRequirements.RequirementService.RejectRequirementRequest request) {
            return base.Channel.RejectRequirement(request);
        }
        
        public void RejectRequirement(long companyId, long projectId, long requirementId, string encUsername) {
            SocialRequirements.RequirementService.RejectRequirementRequest inValue = new SocialRequirements.RequirementService.RejectRequirementRequest();
            inValue.Body = new SocialRequirements.RequirementService.RejectRequirementRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.projectId = projectId;
            inValue.Body.requirementId = requirementId;
            inValue.Body.encUsername = encUsername;
            SocialRequirements.RequirementService.RejectRequirementResponse retVal = ((SocialRequirements.RequirementService.RequirementSoap)(this)).RejectRequirement(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SocialRequirements.RequirementService.RejectRequirementResponse> SocialRequirements.RequirementService.RequirementSoap.RejectRequirementAsync(SocialRequirements.RequirementService.RejectRequirementRequest request) {
            return base.Channel.RejectRequirementAsync(request);
        }
        
        public System.Threading.Tasks.Task<SocialRequirements.RequirementService.RejectRequirementResponse> RejectRequirementAsync(long companyId, long projectId, long requirementId, string encUsername) {
            SocialRequirements.RequirementService.RejectRequirementRequest inValue = new SocialRequirements.RequirementService.RejectRequirementRequest();
            inValue.Body = new SocialRequirements.RequirementService.RejectRequirementRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.projectId = projectId;
            inValue.Body.requirementId = requirementId;
            inValue.Body.encUsername = encUsername;
            return ((SocialRequirements.RequirementService.RequirementSoap)(this)).RejectRequirementAsync(inValue);
        }
    }
}
